// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Branch struct {
	ID        string
	Code      string
	Name      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type GrainType struct {
	ID                   string
	Code                 string
	Name                 string
	PurchasePriceMinor   int64
	InventoryTargetGrams int64
	MarginPolicyBps      int32
	Active               bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Scale struct {
	ID         string
	BranchID   string
	ScaleID    string
	Name       string
	ApiKeyHash string
	Active     bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type TransportTransaction struct {
	ID                         string
	BranchID                   string
	TruckID                    string
	GrainTypeID                string
	Status                     string
	PurchasePriceMinorSnapshot int64
	MarginPolicyBpsSnapshot    int32
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type Truck struct {
	ID              string
	Plate           string
	TareWeightGrams int64
	Active          bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
