// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: registrations.sql

package sqlc

import (
	"context"
)

const cancelTransportTransaction = `-- name: CancelTransportTransaction :one
UPDATE transport_transactions
SET status = 'CANCELLED', updated_at = now()
WHERE id = $1 AND status = 'OPEN'
RETURNING id, branch_id, truck_id, grain_type_id, status, purchase_price_minor_snapshot, margin_policy_bps_snapshot, created_at, updated_at
`

func (q *Queries) CancelTransportTransaction(ctx context.Context, id string) (TransportTransaction, error) {
	row := q.db.QueryRow(ctx, cancelTransportTransaction, id)
	var i TransportTransaction
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.TruckID,
		&i.GrainTypeID,
		&i.Status,
		&i.PurchasePriceMinorSnapshot,
		&i.MarginPolicyBpsSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (id, code, name)
VALUES ($1, $2, $3)
RETURNING id, code, name, active, created_at, updated_at
`

type CreateBranchParams struct {
	ID   string
	Code string
	Name string
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch, arg.ID, arg.Code, arg.Name)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGrainType = `-- name: CreateGrainType :one
INSERT INTO grain_types (id, code, name, purchase_price_minor, inventory_target_grams, margin_policy_bps)
VALUES ($1, $2, $3, $4,
        $5, $6)
RETURNING id, code, name, purchase_price_minor, inventory_target_grams, margin_policy_bps, active, created_at, updated_at
`

type CreateGrainTypeParams struct {
	ID                   string
	Code                 string
	Name                 string
	PurchasePriceMinor   int64
	InventoryTargetGrams int64
	MarginPolicyBps      int32
}

func (q *Queries) CreateGrainType(ctx context.Context, arg CreateGrainTypeParams) (GrainType, error) {
	row := q.db.QueryRow(ctx, createGrainType,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.PurchasePriceMinor,
		arg.InventoryTargetGrams,
		arg.MarginPolicyBps,
	)
	var i GrainType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PurchasePriceMinor,
		&i.InventoryTargetGrams,
		&i.MarginPolicyBps,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScale = `-- name: CreateScale :one
INSERT INTO scales (id, branch_id, scale_id, name, api_key_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, branch_id, scale_id, name, api_key_hash, active, created_at, updated_at
`

type CreateScaleParams struct {
	ID         string
	BranchID   string
	ScaleID    string
	Name       string
	ApiKeyHash string
}

func (q *Queries) CreateScale(ctx context.Context, arg CreateScaleParams) (Scale, error) {
	row := q.db.QueryRow(ctx, createScale,
		arg.ID,
		arg.BranchID,
		arg.ScaleID,
		arg.Name,
		arg.ApiKeyHash,
	)
	var i Scale
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ScaleID,
		&i.Name,
		&i.ApiKeyHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransportTransaction = `-- name: CreateTransportTransaction :one
INSERT INTO transport_transactions (
    id, branch_id, truck_id, grain_type_id, status, purchase_price_minor_snapshot, margin_policy_bps_snapshot
)
VALUES (
    $1, $2, $3, $4, 'OPEN',
    $5, $6
)
RETURNING id, branch_id, truck_id, grain_type_id, status, purchase_price_minor_snapshot, margin_policy_bps_snapshot, created_at, updated_at
`

type CreateTransportTransactionParams struct {
	ID                         string
	BranchID                   string
	TruckID                    string
	GrainTypeID                string
	PurchasePriceMinorSnapshot int64
	MarginPolicyBpsSnapshot    int32
}

func (q *Queries) CreateTransportTransaction(ctx context.Context, arg CreateTransportTransactionParams) (TransportTransaction, error) {
	row := q.db.QueryRow(ctx, createTransportTransaction,
		arg.ID,
		arg.BranchID,
		arg.TruckID,
		arg.GrainTypeID,
		arg.PurchasePriceMinorSnapshot,
		arg.MarginPolicyBpsSnapshot,
	)
	var i TransportTransaction
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.TruckID,
		&i.GrainTypeID,
		&i.Status,
		&i.PurchasePriceMinorSnapshot,
		&i.MarginPolicyBpsSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTruck = `-- name: CreateTruck :one
INSERT INTO trucks (id, plate, tare_weight_grams)
VALUES ($1, $2, $3)
RETURNING id, plate, tare_weight_grams, active, created_at, updated_at
`

type CreateTruckParams struct {
	ID              string
	Plate           string
	TareWeightGrams int64
}

func (q *Queries) CreateTruck(ctx context.Context, arg CreateTruckParams) (Truck, error) {
	row := q.db.QueryRow(ctx, createTruck, arg.ID, arg.Plate, arg.TareWeightGrams)
	var i Truck
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.TareWeightGrams,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateBranch = `-- name: DeactivateBranch :one
UPDATE branches SET active = FALSE, updated_at = now()
WHERE id = $1 AND active = TRUE
RETURNING id, code, name, active, created_at, updated_at
`

func (q *Queries) DeactivateBranch(ctx context.Context, id string) (Branch, error) {
	row := q.db.QueryRow(ctx, deactivateBranch, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateGrainType = `-- name: DeactivateGrainType :one
UPDATE grain_types SET active = FALSE, updated_at = now()
WHERE id = $1 AND active = TRUE
RETURNING id, code, name, purchase_price_minor, inventory_target_grams, margin_policy_bps, active, created_at, updated_at
`

func (q *Queries) DeactivateGrainType(ctx context.Context, id string) (GrainType, error) {
	row := q.db.QueryRow(ctx, deactivateGrainType, id)
	var i GrainType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PurchasePriceMinor,
		&i.InventoryTargetGrams,
		&i.MarginPolicyBps,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateScale = `-- name: DeactivateScale :one
UPDATE scales SET active = FALSE, updated_at = now()
WHERE id = $1 AND active = TRUE
RETURNING id, branch_id, scale_id, name, api_key_hash, active, created_at, updated_at
`

func (q *Queries) DeactivateScale(ctx context.Context, id string) (Scale, error) {
	row := q.db.QueryRow(ctx, deactivateScale, id)
	var i Scale
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ScaleID,
		&i.Name,
		&i.ApiKeyHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateTruck = `-- name: DeactivateTruck :one
UPDATE trucks SET active = FALSE, updated_at = now()
WHERE id = $1 AND active = TRUE
RETURNING id, plate, tare_weight_grams, active, created_at, updated_at
`

func (q *Queries) DeactivateTruck(ctx context.Context, id string) (Truck, error) {
	row := q.db.QueryRow(ctx, deactivateTruck, id)
	var i Truck
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.TareWeightGrams,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveBranch = `-- name: GetActiveBranch :one
SELECT id, code, name, active, created_at, updated_at FROM branches WHERE id = $1 AND active = TRUE
`

func (q *Queries) GetActiveBranch(ctx context.Context, id string) (Branch, error) {
	row := q.db.QueryRow(ctx, getActiveBranch, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveGrainType = `-- name: GetActiveGrainType :one
SELECT id, code, name, purchase_price_minor, inventory_target_grams, margin_policy_bps, active, created_at, updated_at FROM grain_types WHERE id = $1 AND active = TRUE
`

func (q *Queries) GetActiveGrainType(ctx context.Context, id string) (GrainType, error) {
	row := q.db.QueryRow(ctx, getActiveGrainType, id)
	var i GrainType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PurchasePriceMinor,
		&i.InventoryTargetGrams,
		&i.MarginPolicyBps,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveScale = `-- name: GetActiveScale :one
SELECT id, branch_id, scale_id, name, api_key_hash, active, created_at, updated_at FROM scales WHERE id = $1 AND active = TRUE
`

func (q *Queries) GetActiveScale(ctx context.Context, id string) (Scale, error) {
	row := q.db.QueryRow(ctx, getActiveScale, id)
	var i Scale
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ScaleID,
		&i.Name,
		&i.ApiKeyHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTruck = `-- name: GetActiveTruck :one
SELECT id, plate, tare_weight_grams, active, created_at, updated_at FROM trucks WHERE id = $1 AND active = TRUE
`

func (q *Queries) GetActiveTruck(ctx context.Context, id string) (Truck, error) {
	row := q.db.QueryRow(ctx, getActiveTruck, id)
	var i Truck
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.TareWeightGrams,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranch = `-- name: GetBranch :one
SELECT id, code, name, active, created_at, updated_at FROM branches WHERE id = $1
`

func (q *Queries) GetBranch(ctx context.Context, id string) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranch, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGrainType = `-- name: GetGrainType :one
SELECT id, code, name, purchase_price_minor, inventory_target_grams, margin_policy_bps, active, created_at, updated_at FROM grain_types WHERE id = $1
`

func (q *Queries) GetGrainType(ctx context.Context, id string) (GrainType, error) {
	row := q.db.QueryRow(ctx, getGrainType, id)
	var i GrainType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PurchasePriceMinor,
		&i.InventoryTargetGrams,
		&i.MarginPolicyBps,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScale = `-- name: GetScale :one
SELECT id, branch_id, scale_id, name, api_key_hash, active, created_at, updated_at FROM scales WHERE id = $1
`

func (q *Queries) GetScale(ctx context.Context, id string) (Scale, error) {
	row := q.db.QueryRow(ctx, getScale, id)
	var i Scale
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ScaleID,
		&i.Name,
		&i.ApiKeyHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransportTransaction = `-- name: GetTransportTransaction :one
SELECT id, branch_id, truck_id, grain_type_id, status, purchase_price_minor_snapshot, margin_policy_bps_snapshot, created_at, updated_at FROM transport_transactions WHERE id = $1
`

func (q *Queries) GetTransportTransaction(ctx context.Context, id string) (TransportTransaction, error) {
	row := q.db.QueryRow(ctx, getTransportTransaction, id)
	var i TransportTransaction
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.TruckID,
		&i.GrainTypeID,
		&i.Status,
		&i.PurchasePriceMinorSnapshot,
		&i.MarginPolicyBpsSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTruck = `-- name: GetTruck :one
SELECT id, plate, tare_weight_grams, active, created_at, updated_at FROM trucks WHERE id = $1
`

func (q *Queries) GetTruck(ctx context.Context, id string) (Truck, error) {
	row := q.db.QueryRow(ctx, getTruck, id)
	var i Truck
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.TareWeightGrams,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranches = `-- name: ListBranches :many
SELECT id, code, name, active, created_at, updated_at FROM branches ORDER BY code
`

func (q *Queries) ListBranches(ctx context.Context) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrainTypes = `-- name: ListGrainTypes :many
SELECT id, code, name, purchase_price_minor, inventory_target_grams, margin_policy_bps, active, created_at, updated_at FROM grain_types ORDER BY code
`

func (q *Queries) ListGrainTypes(ctx context.Context) ([]GrainType, error) {
	rows, err := q.db.Query(ctx, listGrainTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrainType
	for rows.Next() {
		var i GrainType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.PurchasePriceMinor,
			&i.InventoryTargetGrams,
			&i.MarginPolicyBps,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScales = `-- name: ListScales :many
SELECT id, branch_id, scale_id, name, api_key_hash, active, created_at, updated_at FROM scales ORDER BY scale_id
`

func (q *Queries) ListScales(ctx context.Context) ([]Scale, error) {
	rows, err := q.db.Query(ctx, listScales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scale
	for rows.Next() {
		var i Scale
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.ScaleID,
			&i.Name,
			&i.ApiKeyHash,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransportTransactions = `-- name: ListTransportTransactions :many
SELECT id, branch_id, truck_id, grain_type_id, status, purchase_price_minor_snapshot, margin_policy_bps_snapshot, created_at, updated_at FROM transport_transactions ORDER BY created_at DESC, id
`

func (q *Queries) ListTransportTransactions(ctx context.Context) ([]TransportTransaction, error) {
	rows, err := q.db.Query(ctx, listTransportTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransportTransaction
	for rows.Next() {
		var i TransportTransaction
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.TruckID,
			&i.GrainTypeID,
			&i.Status,
			&i.PurchasePriceMinorSnapshot,
			&i.MarginPolicyBpsSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrucks = `-- name: ListTrucks :many
SELECT id, plate, tare_weight_grams, active, created_at, updated_at FROM trucks ORDER BY plate
`

func (q *Queries) ListTrucks(ctx context.Context) ([]Truck, error) {
	rows, err := q.db.Query(ctx, listTrucks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Truck
	for rows.Next() {
		var i Truck
		if err := rows.Scan(
			&i.ID,
			&i.Plate,
			&i.TareWeightGrams,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches
SET code = $1, name = $2, updated_at = now()
WHERE id = $3 AND active = TRUE
RETURNING id, code, name, active, created_at, updated_at
`

type UpdateBranchParams struct {
	Code string
	Name string
	ID   string
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch, arg.Code, arg.Name, arg.ID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGrainType = `-- name: UpdateGrainType :one
UPDATE grain_types
SET code = $1, name = $2, purchase_price_minor = $3,
    inventory_target_grams = $4, margin_policy_bps = $5,
    updated_at = now()
WHERE id = $6 AND active = TRUE
RETURNING id, code, name, purchase_price_minor, inventory_target_grams, margin_policy_bps, active, created_at, updated_at
`

type UpdateGrainTypeParams struct {
	Code                 string
	Name                 string
	PurchasePriceMinor   int64
	InventoryTargetGrams int64
	MarginPolicyBps      int32
	ID                   string
}

func (q *Queries) UpdateGrainType(ctx context.Context, arg UpdateGrainTypeParams) (GrainType, error) {
	row := q.db.QueryRow(ctx, updateGrainType,
		arg.Code,
		arg.Name,
		arg.PurchasePriceMinor,
		arg.InventoryTargetGrams,
		arg.MarginPolicyBps,
		arg.ID,
	)
	var i GrainType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PurchasePriceMinor,
		&i.InventoryTargetGrams,
		&i.MarginPolicyBps,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScale = `-- name: UpdateScale :one
UPDATE scales
SET branch_id = $1, scale_id = $2, name = $3,
    api_key_hash = $4, updated_at = now()
WHERE id = $5 AND active = TRUE
RETURNING id, branch_id, scale_id, name, api_key_hash, active, created_at, updated_at
`

type UpdateScaleParams struct {
	BranchID   string
	ScaleID    string
	Name       string
	ApiKeyHash string
	ID         string
}

func (q *Queries) UpdateScale(ctx context.Context, arg UpdateScaleParams) (Scale, error) {
	row := q.db.QueryRow(ctx, updateScale,
		arg.BranchID,
		arg.ScaleID,
		arg.Name,
		arg.ApiKeyHash,
		arg.ID,
	)
	var i Scale
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ScaleID,
		&i.Name,
		&i.ApiKeyHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTruck = `-- name: UpdateTruck :one
UPDATE trucks
SET plate = $1, tare_weight_grams = $2, updated_at = now()
WHERE id = $3 AND active = TRUE
RETURNING id, plate, tare_weight_grams, active, created_at, updated_at
`

type UpdateTruckParams struct {
	Plate           string
	TareWeightGrams int64
	ID              string
}

func (q *Queries) UpdateTruck(ctx context.Context, arg UpdateTruckParams) (Truck, error) {
	row := q.db.QueryRow(ctx, updateTruck, arg.Plate, arg.TareWeightGrams, arg.ID)
	var i Truck
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.TareWeightGrams,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
